# Site settings
title: Mark Jan Moorman
description: 'Business Card Page'
url: 'https://mj-moor.github.io/'
baseurl: ''
profilepic: '/images/me.jpeg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Mark Jan Moorman'
  github_username:  mj-moor
  linkedin_username:  mark-jan-moorman-7220b032
  medium_username: mjm_

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
